DOMAIN = "infpro"
DEFAULT_UPDATE_INTERVAL = 180  # Poți pune orice valoare dorești, în secunde
DEFAULT_ORAS = "ALBA IULIA"  # Oraș implicit

LISTA_ORASE = [
    "ABRUD",
    "ADJUD",
    "AGNITA",
    "AIUD",
    "ALBA IULIA",
    "ALBESTI",
    "ALESD",
    "ALEXANDRIA",
    "AMARA",
    "ANINA",
    "ANINOASA",
    "ARAD",
    "ARDUD",
    "AVRIG",
    "AZUGA",
    "BABADAG",
    "BABENI",
    "BACAU",
    "BAIA DE ARAMA",
    "BAIA DE ARIES",
    "BAIA MARE",
    "BAIA SPRIE",
    "BAICOI",
    "BAILE HERCULANE",
    "BAILE OLANESTI",
    "BAILE TUSNAD",
    "BAILESTI",
    "BALAN",
    "BALS",
    "BANEASA",
    "BARAOLT",
    "BARLAD",
    "BASARABI",
    "BECHET",
    "BECLEAN",
    "BEIUS",
    "BERBESTI",
    "BERESTI",
    "BICAZ",
    "BISTRITA",
    "BLAJ",
    "BOCSA",
    "BOLDESTI-SCAENI",
    "BOLINTIN-VALE",
    "BORSA",
    "BORSEC",
    "BOTOSANI",
    "BRAD",
    "BRAGADIRU",
    "BRAILA",
    "BRASOV",
    "BREZOI",
    "BROSTENI",
    "BUCECEA",
    "BUCURESTI",
    "BUDESTI",
    "BUFTEA",
    "BUHUSI",
    "BUMBESTI-JIU",
    "BUSTENI",
    "BUZAU",
    "BUZIAS",
    "CAJVANA",
    "CALAFAT",
    "CALARASI",
    "CALIMANESTI-CACIULATA",
    "CAMPENI",
    "CAMPIA TURZII",
    "CAMPINA",
    "CAMPULUNG",
    "CAMPULUNG MOLDOVENESC",
    "CARACAL",
    "CARANSEBES",
    "CAREI",
    "CAVNIC",
    "CAZANESTI",
    "CEHU SILVANIEI",
    "CERNAVODA",
    "CHISINEU-CRIS",
    "CHITILA",
    "CIACOVA",
    "CISNADIE",
    "CLUJ-NAPOCA",
    "CODLEA",
    "COMANESTI",
    "COMARNIC",
    "CONSTANTA",
    "COPSA MICA",
    "CORABIA",
    "COSTESTI",
    "COVASNA",
    "CRAIOVA",
    "CRISTURU SECUIESC",
    "CUGIR",
    "CURTEA DE ARGES",
    "CURTICI",
    "DABULENI",
    "DARMANESTI",
    "DEJ",
    "DETA",
    "DEVA",
    "DOLHASCA",
    "DOROHOI",
    "DRAGANESTI-OLT",
    "DRAGASANI",
    "DRAGOMIRESTI",
    "DROBETA-TURNU SEVERIN",
    "DUMBRAVENI",
    "FAGARAS",
    "FAGET",
    "FALTICENI",
    "FAUREI",
    "FETESTI",
    "FIENI",
    "FIERBINTI-TARG",
    "FILIASI",
    "FLAMANZI",
    "FOCSANI",
    "FRASIN",
    "FUNDULEA",
    "GAESTI",
    "GALATI",
    "GATAIA",
    "GEOAGIU",
    "GHEORGHENI",
    "GHERLA",
    "GHIMBAV",
    "GIURGIU",
    "GURA HUMORULUI",
    "HARLAU",
    "HARSOVA",
    "HATEG",
    "HOREZU",
    "HUEDIN",
    "HUNEDOARA",
    "IANCA",
    "IASI",
    "IERNUT",
    "INEU",
    "INSURATEI",
    "INTORSURA BUZAULUI",
    "ISACCEA",
    "JIBOU",
    "JIMBOLIA",
    "LEHLIU-GARA",
    "LIPOVA",
    "LITENI",
    "LIVADA",
    "LUDUS",
    "LUGOJ",
    "LUPENI-HR",
    "LUPENI-HU",
    "MACIN",
    "MAGURELE",
    "MANGALIA",
    "MARASESTI",
    "MARGHITA",
    "MEDGIDIA",
    "MEDIAS",
    "MIERCUREA CIUC",
    "MIERCUREA NIRAJULUI",
    "MIERCUREA SIBIULUI",
    "MIHAILESTI",
    "MILISAUTI",
    "MIOVENI",
    "MIZIL",
    "MOINESTI",
    "MOLDOVA NOUA",
    "MORENI",
    "MOTRU",
    "MURGENI",
    "NADLAC",
    "NASAUD",
    "NAVODARI",
    "NEGRESTI",
    "NEGRESTI-OAS",
    "NEGRU VODA",
    "NEHOIU",
    "NOVACI",
    "NUCET",
    "OCNA MURES",
    "OCNA SIBIULUI",
    "OCNELE MARI",
    "ODOBESTI",
    "ODORHEIU SECUIESC",
    "OLTENITA",
    "ONESTI",
    "ORADEA",
    "ORASTIE",
    "ORAVITA",
    "ORSOVA",
    "OTELU ROSU",
    "OTOPENI",
    "OVIDIU",
    "PANCIU",
    "PANCOTA",
    "PANTELIMON",
    "PASCANI",
    "PATARLAGELE",
    "PECICA",
    "PETRILA",
    "PETROSANI",
    "PIATRA NEAMT",
    "PIATRA OLT",
    "PITESTI",
    "PLOIESTI",
    "PLOPENI",
    "POGOANELE",
    "POTCOAVA",
    "PREDEAL",
    "PUCIOASA",
    "RACARI",
    "RADAUTI",
    "RAMNICU SARAT",
    "RAMNICU VALCEA",
    "RASNOV",
    "RECAS",
    "REGHIN",
    "RESITA",
    "ROMAN",
    "ROSIORI DE VEDE",
    "ROVINARI",
    "ROZNOV",
    "RUPEA",
    "SACELE",
    "SALCEA",
    "SALISTE",
    "SALISTEA DE SUS",
    "SALONTA",
    "SANGEORGIU DE MURES",
    "SANGEORGIU DE PADURE",
    "SANNICOLAU MARE",
    "SANTANA",
    "SARMASU",
    "SATU MARE",
    "SAVENI",
    "SCORNICESTI",
    "SEBES",
    "SEBIS",
    "SEGARCEA",
    "SEINI",
    "SFANTU GHEORGHE",
    "SIBIU",
    "SIGHETU MARMATIEI",
    "SIGHISOARA",
    "SIMERIA",
    "SIMLEU SILVANIEI",
    "SINAIA",
    "SIRET",
    "SLANIC",
    "SLANIC-MOLDOVA",
    "SLATINA",
    "SLOBOZIA",
    "SOLCA",
    "SOMCUTA MARE",
    "SOVATA",
    "STEFANESTI-BT",
    "STEFANESTI-AG",
    "STEI",
    "STREHAIA",
    "SUCEAVA",
    "TALMACIU",
    "TANDAREI",
    "TARGOVISTE",
    "TARGU BUJOR",
    "TARGU CARBUNESTI",
    "TARGU FRUMOS",
    "TARGU JIU",
    "TARGU LAPUS",
    "TARGU MURES",
    "TARGU OCNA",
    "TARGU SECUIESC",
    "TARGU-NEAMT",
    "TARNAVENI",
    "TASNAD",
    "TAUTII-MAGHERAUS",
    "TECHIRGHIOL",
    "TECUCI",
    "TEIUS",
    "TICLENI",
    "TIMISOARA",
    "TISMANA",
    "TITU",
    "TOPLITA",
    "TOPOLOVENI",
    "TULCEA",
    "TURCENI",
    "TURDA",
    "TURNU MAGURELE",
    "ULMENI",
    "UNGHENI",
    "URICANI",
    "URZICENI",
    "VALEA LUI MIHAI",
    "VALENII DE MUNTE",
    "VANJU MARE",
    "VASCAU",
    "VASLUI",
    "VATRA DORNEI",
    "VICOVU DE JOS",
    "VICOVU DE SUS",
    "VICTORIA",
    "VIDELE",
    "VISEU DE SUS",
    "VLAHITA",
    "VOLUNTARI",
    "VULCAN",
    "ZALAU",
    "ZARNESTI",
    "ZIMNICEA",
    "ZLATNA"
]

DISPLAY_ORASE = {
    "ABRUD": "Abrud",
    "ADJUD": "Adjud",
    "AGNITA": "Agnita",
    "AIUD": "Aiud",
    "ALBA IULIA": "Alba Iulia",
    "ALBESTI": "Albești",
    "ALESD": "Aleșd",
    "ALEXANDRIA": "Alexandria",
    "AMARA": "Amara",
    "ANINA": "Anina",
    "ANINOASA": "Aninoasa",
    "ARAD": "Arad",
    "ARDUD": "Ardud",
    "AVRIG": "Avrig",
    "AZUGA": "Azuga",
    "BABADAG": "Babadag",
    "BABENI": "Băbeni",
    "BACAU": "Bacău",
    "BAIA DE ARAMA": "Baia de Aramă",
    "BAIA DE ARIES": "Baia de Arieș",
    "BAIA MARE": "Baia Mare",
    "BAIA SPRIE": "Baia Sprie",
    "BAICOI": "Băicoi",
    "BAILE HERCULANE": "Băile Herculane",
    "BAILE OLANESTI": "Băile Olănești",
    "BAILE TUSNAD": "Băile Tușnad",
    "BAILESTI": "Băilești",
    "BALAN": "Bălan",
    "BALS": "Balș",
    "BANEASA": "Băneasa",
    "BARAOLT": "Baraolt",
    "BARLAD": "Bârlad",
    "BASARABI": "Basarabi",
    "BECHET": "Bechet",
    "BECLEAN": "Beclean",
    "BEIUS": "Beiuș",
    "BERBESTI": "Berbești",
    "BERESTI": "Berești",
    "BICAZ": "Bicaz",
    "BISTRITA": "Bistrița",
    "BLAJ": "Blaj",
    "BOCSA": "Bocșa",
    "BOLDESTI-SCAENI": "Boldești-Scăeni",
    "BOLINTIN-VALE": "Bolintin-Vale",
    "BORSA": "Borșa",
    "BORSEC": "Borsec",
    "BOTOSANI": "Botoșani",
    "BRAD": "Brad",
    "BRAGADIRU": "Bragadiru",
    "BRAILA": "Brăila",
    "BRASOV": "Brașov",
    "BREZOI": "Brezoi",
    "BROSTENI": "Broșteni",
    "BUCECEA": "Bucecea",
    "BUCURESTI": "București",
    "BUDESTI": "Budești",
    "BUFTEA": "Buftea",
    "BUHUSI": "Buhuși",
    "BUMBESTI-JIU": "Bumbești-Jiu",
    "BUSTENI": "Bușteni",
    "BUZAU": "Buzău",
    "BUZIAS": "Buziaș",
    "CAJVANA": "Cajvana",
    "CALAFAT": "Calafat",
    "CALARASI": "Călărași",
    "CALIMANESTI-CACIULATA": "Călimănești-Căciulata",
    "CAMPENI": "Câmpeni",
    "CAMPIA TURZII": "Câmpia Turzii",
    "CAMPINA": "Câmpina",
    "CAMPULUNG": "Câmpulung",
    "CAMPULUNG MOLDOVENESC": "Câmpulung Moldovenesc",
    "CARACAL": "Caracal",
    "CARANSEBES": "Caransebeș",
    "CAREI": "Carei",
    "CAVNIC": "Cavnic",
    "CAZANESTI": "Căzănești",
    "CEHU SILVANIEI": "Cehu Silvaniei",
    "CERNAVODA": "Cernavodă",
    "CHISINEU-CRIS": "Chișineu-Criș",
    "CHITILA": "Chitila",
    "CIACOVA": "Ciacova",
    "CISNADIE": "Cisnădie",
    "CLUJ-NAPOCA": "Cluj-Napoca",
    "CODLEA": "Codlea",
    "COMANESTI": "Comănești",
    "COMARNIC": "Comarnic",
    "CONSTANTA": "Constanța",
    "COPSA MICA": "Copșa Mică",
    "CORABIA": "Corabia",
    "COSTESTI": "Costești",
    "COVASNA": "Covasna",
    "CRAIOVA": "Craiova",
    "CRISTURU SECUIESC": "Cristuru Secuiesc",
    "CUGIR": "Cugir",
    "CURTEA DE ARGES": "Curtea de Argeș",
    "CURTICI": "Curtici",
    "DABULENI": "Dăbuleni",
    "DARMANESTI": "Dărmănești",
    "DEJ": "Dej",
    "DETA": "Deta",
    "DEVA": "Deva",
    "DOLHASCA": "Dolhasca",
    "DOROHOI": "Dorohoi",
    "DRAGANESTI-OLT": "Drăgănești-Olt",
    "DRAGASANI": "Drăgășani",
    "DRAGOMIRESTI": "Dragomirești",
    "DROBETA-TURNU SEVERIN": "Drobeta-Turnu Severin",
    "DUMBRAVENI": "Dumbrăveni",
    "FAGARAS": "Făgăraș",
    "FAGET": "Făget",
    "FALTICENI": "Fălticeni",
    "FAUREI": "Făurei",
    "FETESTI": "Fetești",
    "FIENI": "Fieni",
    "FIERBINTI-TARG": "Fierbinți-Târg",
    "FILIASI": "Filiași",
    "FLAMANZI": "Flămânzi",
    "FOCSANI": "Focșani",
    "FRASIN": "Frasin",
    "FUNDULEA": "Fundulea",
    "GAESTI": "Găești",
    "GALATI": "Galați",
    "GATAIA": "Gătaia",
    "GEOAGIU": "Geoagiu",
    "GHEORGHENI": "Gheorgheni",
    "GHERLA": "Gherla",
    "GHIMBAV": "Ghimbav",
    "GIURGIU": "Giurgiu",
    "GURA HUMORULUI": "Gura Humorului",
    "HARLAU": "Hârlău",
    "HARSOVA": "Hârșova",
    "HATEG": "Hațeg",
    "HOREZU": "Horezu",
    "HUEDIN": "Huedin",
    "HUNEDOARA": "Hunedoara",
    "IANCA": "Ianca",
    "IASI": "Iași",
    "IERNUT": "Iernut",
    "INEU": "Ineu",
    "INSURATEI": "Însurăței",
    "INTORSURA BUZAULUI": "Întorsura Buzăului",
    "ISACCEA": "Isaccea",
    "JIBOU": "Jibou",
    "JIMBOLIA": "Jimbolia",
    "LEHLIU-GARA": "Lehliu-Gară",
    "LIPOVA": "Lipova",
    "LITENI": "Liteni",
    "LIVADA": "Livada",
    "LUDUS": "Luduș",
    "LUGOJ": "Lugoj",
    "LUPENI-HR": "Lupeni (Județul Harghita)",
    "LUPENI-HU": "Lupeni (Județul Hunedoara)",
    "MACIN": "Măcin",
    "MAGURELE": "Măgurele",
    "MANGALIA": "Mangalia",
    "MARASESTI": "Mărășești",
    "MARGHITA": "Marghita",
    "MEDGIDIA": "Medgidia",
    "MEDIAS": "Mediaș",
    "MIERCUREA CIUC": "Miercurea Ciuc",
    "MIERCUREA NIRAJULUI": "Miercurea Nirajului",
    "MIERCUREA SIBIULUI": "Miercurea Sibiului",
    "MIHAILESTI": "Mihăilești",
    "MILISAUTI": "Milișăuți",
    "MIOVENI": "Mioveni",
    "MIZIL": "Mizil",
    "MOINESTI": "Moinești",
    "MOLDOVA NOUA": "Moldova Nouă",
    "MORENI": "Moreni",
    "MOTRU": "Motru",
    "MURGENI": "Murgeni",
    "NADLAC": "Nădlac",
    "NASAUD": "Năsăud",
    "NAVODARI": "Năvodari",
    "NEGRESTI": "Negrești",
    "NEGRESTI-OAS": "Negrești-Oaș",
    "NEGRU VODA": "Negru Vodă",
    "NEHOIU": "Nehoiu",
    "NOVACI": "Novaci",
    "NUCET": "Nucet",
    "OCNA MURES": "Ocna Mureș",
    "OCNA SIBIULUI": "Ocna Sibiului",
    "OCNELE MARI": "Ocnele Mari",
    "ODOBESTI": "Odobești",
    "ODORHEIU SECUIESC": "Odorheiu Secuiesc",
    "OLTENITA": "Oltenița",
    "ONESTI": "Onești",
    "ORADEA": "Oradea",
    "ORASTIE": "Orăștie",
    "ORAVITA": "Oravița",
    "ORSOVA": "Orșova",
    "OTELU ROSU": "Oțelu Roșu",
    "OTOPENI": "Otopeni",
    "OVIDIU": "Ovidiu",
    "PANCIU": "Panciu",
    "PANCOTA": "Pâncota",
    "PANTELIMON": "Pantelimon",
    "PASCANI": "Pașcani",
    "PATARLAGELE": "Pătârlagele",
    "PECICA": "Pecica",
    "PETRILA": "Petrila",
    "PETROSANI": "Petroșani",
    "PIATRA NEAMT": "Piatra Neamț",
    "PIATRA OLT": "Piatra Olt",
    "PITESTI": "Pitești",
    "PLOIESTI": "Ploiești",
    "PLOPENI": "Plopeni",
    "POGOANELE": "Pogoanele",
    "POTCOAVA": "Potcoava",
    "PREDEAL": "Predeal",
    "PUCIOASA": "Pucioasa",
    "RACARI": "Răcari",
    "RADAUTI": "Rădăuți",
    "RAMNICU SARAT": "Râmnicu Sărat",
    "RAMNICU VALCEA": "Râmnicu Vâlcea",
    "RASNOV": "Râșnov",
    "RECAS": "Recaș",
    "REGHIN": "Reghin",
    "RESITA": "Reșița",
    "ROMAN": "Roman",
    "ROSIORI DE VEDE": "Roșiori de Vede",
    "ROVINARI": "Rovinari",
    "ROZNOV": "Roznov",
    "RUPEA": "Rupea",
    "SACELE": "Săcele",
    "SALCEA": "Salcea",
    "SALISTE": "Săliște",
    "SALISTEA DE SUS": "Săliștea de Sus",
    "SALONTA": "Salonta",
    "SANGEORGIU DE MURES": "Sângeorgiu de Mureș",
    "SANGEORGIU DE PADURE": "Sângeorgiu de Pădure",
    "SANNICOLAU MARE": "Sânnicolau Mare",
    "SANTANA": "Sântana",
    "SARMASU": "Sărmașu",
    "SATU MARE": "Satu Mare",
    "SAVENI": "Săveni",
    "SCORNICESTI": "Scornicești",
    "SEBES": "Sebeș",
    "SEBIS": "Sebiș",
    "SEGARCEA": "Segarcea",
    "SEINI": "Seini",
    "SFANTU GHEORGHE": "Sfântu Gheorghe",
    "SIBIU": "Sibiu",
    "SIGHETU MARMATIEI": "Sighetu Marmației",
    "SIGHISOARA": "Sighișoara",
    "SIMERIA": "Simeria",
    "SIMLEU SILVANIEI": "Șimleu Silvaniei",
    "SINAIA": "Sinaia",
    "SIRET": "Siret",
    "SLANIC": "Slănic",
    "SLANIC-MOLDOVA": "Slănic-Moldova",
    "SLATINA": "Slatina",
    "SLOBOZIA": "Slobozia",
    "SOLCA": "Solca",
    "SOMCUTA MARE": "Șomcuta Mare",
    "SOVATA": "Sovata",
    "STEFANESTI-BT": "Ștefănești (Județul Botoșani)",
    "STEFANESTI-AG": "Ștefănești (Județul Argeș)",
    "STEI": "Ștei",
    "STREHAIA": "Strehaia",
    "SUCEAVA": "Suceava",
    "TALMACIU": "Tălmaciu",
    "TANDAREI": "Țăndărei",
    "TARGOVISTE": "Târgoviște",
    "TARGU BUJOR": "Târgu Bujor",
    "TARGU CARBUNESTI": "Târgu Cărbunești",
    "TARGU FRUMOS": "Târgu Frumos",
    "TARGU JIU": "Târgu Jiu",
    "TARGU LAPUS": "Târgu Lăpuș",
    "TARGU MURES": "Târgu Mureș",
    "TARGU OCNA": "Târgu Ocna",
    "TARGU SECUIESC": "Târgu Secuiesc",
    "TARGU-NEAMT": "Târgu Neamț",
    "TARNAVENI": "Târnăveni",
    "TASNAD": "Tășnad",
    "TAUTII-MAGHERAUS": "Tăuții-Măgherăuș",
    "TECHIRGHIOL": "Techirghiol",
    "TECUCI": "Tecuci",
    "TEIUS": "Teiuș",
    "TICLENI": "Țicleni",
    "TIMISOARA": "Timișoara",
    "TISMANA": "Tismana",
    "TITU": "Titu",
    "TOPLITA": "Toplița",
    "TOPOLOVENI": "Topoloveni",
    "TULCEA": "Tulcea",
    "TURCENI": "Turceni",
    "TURDA": "Turda",
    "TURNU MAGURELE": "Turnu Măgurele",
    "ULMENI": "Ulmeni",
    "UNGHENI": "Ungheni",
    "URICANI": "Uricani",
    "URZICENI": "Urziceni",
    "VALEA LUI MIHAI": "Valea lui Mihai",
    "VALENII DE MUNTE": "Vălenii de Munte",
    "VANJU MARE": "Vânju Mare",
    "VASCAU": "Vașcău",
    "VASLUI": "Vaslui",
    "VATRA DORNEI": "Vatra Dornei",
    "VICOVU DE JOS": "Vicovu de Jos",
    "VICOVU DE SUS": "Vicovu de Sus",
    "VICTORIA": "Victoria",
    "VIDELE": "Videle",
    "VISEU DE SUS": "Vișeu de Sus",
    "VLAHITA": "Vlăhița",
    "VOLUNTARI": "Voluntari",
    "VULCAN": "Vulcan",
    "ZALAU": "Zalău",
    "ZARNESTI": "Zărnești",
    "ZIMNICEA": "Zimnicea",
    "ZLATNA": "Zlatna"
}


LISTA_JUDET = [
    "AB", "AR", "AG", "BC", "BH", "BN", "BR", "BT", "BV", "BZ",
    "CS", "CL", "CJ", "CT", "CV", "DB", "DJ", "GL", "GR", "GJ",
    "HR", "HD", "IL", "IS", "IF", "MM", "MH", "MS", "NT", "OT",
    "PH", "SM", "SJ", "SB", "SV", "TR", "TM", "TL", "VS", "VL",
    "VN", "B"
]

DISPLAY_JUDETE = {
    "AB": "Alba",
    "AR": "Arad",
    "AG": "Argeș",
    "BC": "Bacău",
    "BH": "Bihor",
    "BN": "Bistrița-Năsăud",
    "BR": "Brăila",
    "BT": "Botoșani",
    "BV": "Brașov",
    "BZ": "Buzău",
    "CS": "Caraș-Severin",
    "CL": "Călărași",
    "CJ": "Cluj",
    "CT": "Constanța",
    "CV": "Covasna",
    "DB": "Dâmbovița",
    "DJ": "Dolj",
    "GL": "Galați",
    "GR": "Giurgiu",
    "GJ": "Gorj",
    "HR": "Harghita",
    "HD": "Hunedoara",
    "IL": "Ialomița",
    "IS": "Iași",
    "IF": "Ilfov",
    "MM": "Maramureș",
    "MH": "Mehedinți",
    "MS": "Mureș",
    "NT": "Neamț",
    "OT": "Olt",
    "PH": "Prahova",
    "SM": "Satu Mare",
    "SJ": "Sălaj",
    "SB": "Sibiu",
    "SV": "Suceava",
    "TR": "Teleorman",
    "TM": "Timiș",
    "TL": "Tulcea",
    "VS": "Vaslui",
    "VL": "Vâlcea",
    "VN": "Vrancea",
    "B": "București"
}


# URL-ul de unde se preiau datele
DATA_URL = "http://shakemap4.infp.ro/atlas/data/event.pf"

# Denumiri traduse pentru atribute
ATTRIBUTE_TRANSLATIONS = {
    "smevid": "ID",
    "mag_ml": "Magnitudine",
    "mag_mw": "Magnitudinea Momentului (Mw)",
    "origin_time": "Ora (UTC)",
    "local_time": "Ora locală",
    "elat": "Latitudine",
    "elon": "Longitudine",
    "depth": "Adâncime (km)",
    "location": "Zonă",
    "intensity": "Intensitate",
}
